# Generated by Django 4.0.5 on 2022-07-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_keapauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckfrontStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=5)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Checkfront status',
                'verbose_name_plural': 'Checkfront statuses',
            },
        ),
    ]
